import {MINUTE_IN_SECONDS, HOUR_IN_SECONDS} from '../math/timestamp-constants'

export const PURCHASING_FACTOR = 0.95

export const ROBOT_TINKER_INCREASE_LUCK = 0.6
export const ROBOT_TINKER_CHANGE = 0.05

export const EMPLOYMENT_PROTECTION_SECONDS = 30 * MINUTE_IN_SECONDS
export const EMPLOYMENT_TALENT_MODIFICATION_SECONDS = 6 * HOUR_IN_SECONDS

export const MALL_MIN_PEOPLE = 3
export const MALL_MAX_PEOPLE = 7

export const MALL_PRODUCTION_TIME_IN_SECONDS = MINUTE_IN_SECONDS * 5
